### ISSUE TITLE
Customize the clock

### ISSUE THREAD

**Issue by guisantosfr** [guisantosfr/Javascript30#1]
# The JS + CSS clock needs the following changes:

1 - Different heights to the hands (**solved**)
2 - A different color to the second hand
3 - Show the exact hour in the screen (centralized above the clock)
4 - Fix the bug when the hands go to 360 degrees

Any of the changes will be welcome

**Comment by jlangdesign** [comment]
Hi! I'd be happy to work on this.

**Comment by guisantosfr** [comment]
Hi! Ok.

**Comment by beumsk** [comment]
I worked on the 1st point and will work on the second one :)

**Comment by jlangdesign** [comment]
@beumsk Okay, I'll try the 3rd and the 4th then!

**Comment by jlangdesign** [comment]
I have submitted a pull request for Items 3 and 4.

**Comment by guisantosfr** [comment]
Nice Work! Thanks :)
